### ISSUE TITLE
Mobile responsive issue - home page 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/agent247.ai#1]
@codextiny 

support@homeowner.ai
M!l3st0nesL@bs

Please make this section mobile responsive on [home page ](https://agent247.ai/)
![image](https://github.com/user-attachments/assets/ff86281e-051f-4e6c-9e36-619ca156ae37)

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/591a4e0d-a6e9-43a6-8465-9c15c0558016)

you guys created this section with layout, used separate CTA, we need to change the layout then learn more will stack right after description of every card in responsive ...

**Comment by shannonbaldwin** [comment]
@codextiny I changed the layout. Thank you.
