### ISSUE TITLE
Font color in footer

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/agent247.ai#2]
@codextiny

Can you please help change the color font to headline and then the primary color as the hover color in footer of the [home page?](https://agent247.ai/) 

![image](https://github.com/user-attachments/assets/eb3a6a4a-33fc-48e1-8f32-961a88fe3f99)

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/5bc1b496-b2fe-4ac7-8618-432080e22415)

We have updated the color with custom code because default color is already set for a tag generically. and there is no option to change color of a tag directly .

Thanks
