### ISSUE TITLE
Custom sign in link in header

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/agent247.ai#3]
@codextiny 

Please make this URL in the header open in a new tab. I could not figure out how to do that.

![image](https://github.com/user-attachments/assets/e40f4868-1f40-4315-bf08-b44cc4387955)

![image](https://github.com/user-attachments/assets/edb6f7ea-3fac-4942-88cf-4200e2ccead5)

**Comment by codextiny** [comment]
@shannonbaldwin 

Please see reply [here](https://github.com/shannonbaldwin/agent247.ai/issues/4)
