### ISSUE TITLE
Menu on home page

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/agent247.ai#4]
@codextiny 

Please make the home purchase page link to www.onehome.com and open in a new tab. I could not figure out how to do this.

![image](https://github.com/user-attachments/assets/cf58bf98-636a-4178-b797-fb4a4a46c19e)

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/dbd4a020-b719-4200-9a5d-00be9ab1932a)

from screen option you can add option to menu to open link in new tab ...

Thanks
